import type { Metadata } from 'next';
import './globals.css';
import { Navbar, MainHeader } from '@/components';
import { Providers } from '@/providers';

export const metadata: Metadata = {
  title: 'SNA Support and inspire',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainHeader />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
